__title__ = 'GEO-Tresor'
__version__ = '1'
__build__ = 0x040901
__build_string__ = 'v4.9.2_Wed Jul 23 04:53:37 2025 -0400'
__django_version__ = '4.2'
__author__ = 'Direction des Systèmes d\'Information" (DSI)'
__author_email__ = 'ladiehismael9@gmail.com'
__description__ = 'Gestion des documents de la DTG Bureau Opposition'
__license__ = 'GPL 2.0'
__copyright_short__ = '2025 Ministère du Budget'
__copyright__ = '{} {}'.format('Copyright', __copyright_short__)
__website__ = 'https://budget.gouv.dj/dsi/'